### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by parasharrajat** [webextension-toolbox/webextension-toolbox#373] opened 2020-12-12 17:52 UTC
Hey, I think we can build up for Safari as well. 
[Safari Web Extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions).

_Originally posted by @parasharrajat in https://github.com/webextension-toolbox/webextension-toolbox/issues/78#issuecomment-743791654_

**Comment by here-nerd** [comment] 2020-12-28 09:44
Currently, the webextension-toolbox does not recognize 'safari' as a build parameter.

**Comment by parasharrajat** [comment] 2020-12-29 20:27
I meant to extend the toolbox for safari as well.

**Comment by here-nerd** [comment] 2020-12-30 15:54
I get the point. Indeed it would be very nice to fully support Safari Web Extension build. Currently, Safari offers a converter cli 'xcrun' which will pack ie. a chrome web extension into an xcode project. Then you can sign / launch a Safari Web Extension from there. 

What is exactly your proposal? Which part of this flow should webextension-toolbox support? 

I think a very small step e.g. by just fully recognizing the term 'safari' as a build parameter:
`npx webextension-toolbox build safari`
would already be a good start. Currently, this will build an extension into a folder called /safari but the safari specific manifest keys won't work.

**Comment by parasharrajat** [comment] 2021-01-01 13:30
@here-nerd  Exactly, we can hook converter cli into the build tool and add safari build parameters. This will just play nicely for most of the things and then we can add types support from the https://www.npmjs.com/package/@types/chrome/v/0.0.127, if possible.

I don't own a mac otherwise I would have set a pull request.

**Comment by balcsida** [comment] 2021-01-03 16:55
Hi @parasharrajat,

Thank you for bringing this up again.
Currently, I don't own any macOS devices either, but I'm checking the offerings of MacStadium.
I will try to save up to rent one in the coming months and check this idea, if possible.

Regardless of that, this is free to be picked up by anyone who would like to pursue this idea.

**Comment by here-nerd** [comment] 2021-01-11 14:53
I think I can give it a try. But let's first agree on what should be the expected behaviour. Here is my proposal:
At the minimum, the new feature should just do this:
- add safari build parameters with manifest keys support.

Next step:
- hook to an xcode cli build command so that a developer won't have to open xcode during development at all.

Out of scope:
- xcrun (the converter) should be the responsibility of the developer to run the converter herself. Essentially, you need to run this once and potentially you WILL change the xcode project files in xcode e.g. bundle id, app icon, build version, ... hence, I propose to leave this out because that is beyond the responsiblity of webextension-toolbox.

Please comment.

**Comment by parasharrajat** [comment] 2021-01-12 16:47
Good one. Fire up.

**Comment by here-nerd** [comment] 2021-01-28 20:01
@balcsida, please review my PR in the webpack-webextension-plugin repo. 
https://github.com/webextension-toolbox/webpack-webextension-plugin/pull/89

Apparently, I need this code change in webpack-webextension-plugin in order to support safari keyword. After a merge, I will submit another PR for webextension-toolbox.

**Comment by balcsida** [comment] 2021-02-10 08:16
Hi @here-nerd,

Sure, PR merged. 😉

**Comment by here-nerd** [comment] 2021-09-30 11:46
apparently, after wwdc2021, Apple has updated the [page](https://developer.apple.com/documentation/safariservices/safari_web_extensions/updating_a_safari_web_extension) with an instruction how to build a web extension using xcode commandline in an external editor. (I have been (not actively) looking for this for quite sometimes :( )

`xcodebuild -scheme HelloWorld\ \(macOS\) build`

then, we can include this in the webextension-toolbox cli. I think I need a hint how can I do what with webpack stuffs.. then I file a PR for it.

**Comment by tm1000** [comment] 2022-04-06 20:41
I think this is pretty much done unless we specifically want to implement `xcode-build-webpack-plugin` but I dont think that's a good idea because there seem to be additional sets you must take before you can use `xcode-build-webpack-plugin` that can't be automated. Let me know if I'm wrong here

**Comment by csandman** [comment] 2022-04-06 21:46
Overall, it could be automated, but the steps to do so aren't as straightforward as the rest.

To answer your direct question, for the conversion process, it uses the directory which is the last argument in `safari-web-extension-converter` as the _source_ for the safari extension, and it includes that source in the output, so they can't be the same directory.  The resulting safari extension does ultimately still use that source directory (`./dist/safari`) in place for changes.  Idk if that makes sense, let me know if you need me to clarify.

And as far as setting it up automatically goes, it could be part of the yeoman generator if you wanted it to be (I assume that's where it would make sense to put it), as long as you checked to make sure the OS is right, and probably make it optional because XCode would have to be set up properly for it to work.

The steps to doing that as I see them are:

1. Set up the project like it normally is, and hold on to the name the user provides for the extension
2. Run the `webextension-toolbox dev safari` command to generate the source browser extension for the conversion to be based on.  At this point I believe you could then remove it and allow the user to generate it again when they initially start the app, as I've been able to pull an extension from github and run a dev on it without a problem, it just needs to be there for the converter to work.
3. Run the `safari-web-extension-converter` command using the created `./dist/safari` directory as the source and somewhere else that you decide to put the Safari extension source code that will not be ignored by the `.gitignore`.  (You'd probably have to figure out where best to put this):

```sh
xcrun safari-web-extension-converter --project-location ./safari-extension --bundle-identifier com.<extension name from initial setup> --macos-only ./dist/safari

# --macos-only is so it doesn't create a mobile browser extension
```

4. Add the `xcode-build-webpack-plugin` to the webpack setup, if the user opted in to making a Safari extension (or take the code from it and implement it yourself, I don't care either way).

Additionally, you could also add a script to open the project in XCode when `webextension-toolbox dev safari` is run. This could be done with something like this:

```sh
open -a Xcode safari-extension/<extension-name>/<extension-name>.xcodeproj
```

This isn't a required step but as the user would have to start the actual extension through XCode, it could definitely be helpful.  It might also be possible to run the start command using purely cli but I'm not exactly sure how.

Also, I'd probably add a new `.gitignore` file to the `./safari-extension` directory with a [standard apple app setup of some kind](https://www.toptal.com/developers/gitignore/api/swift,xcode,Cobjective-c,osx).

This whole process could be automated in the initial setup if you so chose, but whether or not you'd want to is up to you.  I figured I'd give you my theoretical setup for making this work either way so you can make an informed decision!  Let me know if you have any other questions!

**Closed** 2022-11-16 00:21 UTC
Labels: enhancement, help wanted, wontfix, prio:minor
